services:
      database:
        image: mysqlserver-compose
        ports: 
            - "1111:3306"
        
        # container_name: containernewmovie
      web :
        build: 
          context: .
        image: crud-app-compose      
        ports: 
            - "2222:2000"
        links: 
          - database
            #condition: service_healthy
          - redis
            #condition: service_started
        restart: always
      redis:
        image: redis
        ports:
            - "6379:6379"
        links: 
            - database
        restart: always
version: '3.0'